# spring.datasource.url=jdbc:mysql://localhost:3306/erp_db
# spring.datasource.username=root
# spring.datasource.password=Mahesh@99

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.schema=debug


server.port=${PORT:8080} ✅